global:
  scrape_interval: 15s
  external_labels:
    monitor: 'monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['0.0.0.0:9090']

  - job_name: 'cAdvisor'
    static_configs:
      - targets: ['0.0.0.0:8080']

  - job_name: 'Node-Exporter'
    static_configs:
      - targets: ['0.0.0.0:9100']

